// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zffrzrctjfzywbxpkbfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZnJ6cmN0amZ6eXdieHBrYmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDYyMDAsImV4cCI6MjA1ODY4MjIwMH0.1Qqbz2ESSgKy_6BeHi_Rb84aYYctiCFTqhgHYSUPsro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);